app/forms/forms_tabls.py
from flask_wtf import FlaskForm as Form
from flask_table import Table, Col, DateCol
from wtforms import StringField, IntegerField, FormField,SelectField, FieldList
import yaml
from flask import url_for
def get_states(return_dict=False):
    import os
    states_abr=r"states_abr.txt"
    dir_path = os.path.dirname(os.path.realpath(__file__))
    states_abr=os.path.join(dir_path, states_abr)
    with open(states_abr) as f:
        abrvs = yaml.load(f)
    if not return_dict:
       return [(v, k) for k,v in abrvs.items()]
    else:
       return abrvs

class StatesForm(Form):
      Local_Name = SelectField(
        "States",
        choices=get_states()
    )

# Declare table to display the data
class changeTable(Table):
    options={"table_id": "change_id"}
    classes = ["table", "table-bordered", "table-striped"]
    date = Col ('Date')
    positiveIncrease = Col("Daily number of confirmed cases")
    positive=Col("Total number of confirmed cases")
    death_increase=Col("Daily number of deaths")
    death = Col("Total number of deaths")



app/__init__.py
from flask import Flask
from config import configLooader
from flask_bootstrap import Bootstrap
from flask_babel import Babel

#https://api.covidtracking.com/v1/states/ca/daily.json
def create_app(config_name="development"):
    '''
    THis mthod is usd to cobfigur the application using th confiur name
    :param config_name: development is th default, it can used to config the app in case of testing and production
    :return:
    '''
    from app.routes import routes as routers_blueprint
    covid_app.register_blueprint(routers_blueprint, url_prefix='/')
    print (configLooader)
    app_config = configLooader.get(config_name)
    covid_app.config.from_object(app_config)
    return covid_app

#creat the application
covid_app = Flask(__name__)
#add flask bootsrap
bootstrap = Bootstrap(covid_app)
#add flask table
babel = Babel(covid_app)



app/routes/__init__.py
from flask import Blueprint
routes= Blueprint('routes', __name__)
import app.routes.route_urls

app/routes/route_urls.py
from . import routes
from flask import request, render_template
from  app.forms.forms_tabls import get_states, StatesForm, changeTable
from app.routes.routes_util import get_data

'''
Contains the application main routes
'''
@routes.route('/',methods=['POST', 'GET'])
def index():
    statesForm=StatesForm()
    if statesForm.validate_on_submit():
        data = request.form.to_dict()
        print (data)
        state=data.get("Local_Name")

        st, values=get_data(state)

        tabel_=changeTable(values)
        return render_template('changes.html', table=tabel_, state=st[0])
    return render_template("index.html", title="Covid update",states_form=statesForm)


app/routes/routes_util.py
from app import covid_app
from datetime import datetime
import requests
import json
from  app.forms.forms_tabls import get_states

#https://api.covidtracking.com/v1/states/ca/daily.json



def get_val(item, val):
    if not item.get(val):
        val = 0
    else:
        val = item.get(val)

    return val

def get_data(state):
    covidtrackingUrl=covid_app.config.get('COVID_TRACK_URL')
    file_name = covid_app.config.get('JSON_FILE_NAME')
    #change the state to a lower case it does not accpt other format
    api_url="%s/%s/%s"%(covidtrackingUrl,state.lower(),file_name)
    resp = requests.get(url=api_url,)
    data = json.loads(resp.text)
    if  isinstance(data, dict):
        if data.get("error")==True:
            return [], []

    returned_values=[]
    format_str = '%y/%m/%d'
    daily_death=0
    for i in range(0, len(data)):
        item=data[i]
        if not item.get("date"):
            continue
        date = datetime.strptime(str(item.get("date")), '%Y%m%d').date().strftime(format_str)
        death=get_val(item, "death")
        deathIncrease=get_val(item, "deathIncrease")
        death_increase=daily_death+deathIncrease


        returned_values.append({"date": date,"positiveIncrease" :get_val(item,"positiveIncrease"), "positive":get_val(item,"positive"), "death": death,"death_increase":death_increase })
    states = get_states(return_dict=True)
    st = [ky for ky, val in states.items() if val == state]
    return st,returned_values

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% import "bootstrap/wtf.html" as wtf %}
{% block head %}

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>
  {% block title %}
         {% if title %}
        {{ title }}
        {% else %}
    Covid-19 update
    {% endif %}
        {% endblock %}
  </title>

    <link rel="stylesheet" href={{url_for('static',filename='css/bootstrap.min.css')}}>
    <script src="static/js/jquery.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/jquery.min.js"></script>
    <link rel="stylesheet" href={{url_for('static',filename='css/jquery.dataTables.min.css')}}>
    <script src="static/js/jquery.dataTables.min.js"></script>


</head>
{% endblock %}

<body>
   <div class="container-fluid">
        <br>
    <h3>Covid-19 Update</h3>
    <br>



        {% block app_content %}

        {% endblock %}
    </div>

</body>
</html>

app/templates/changes.html
{% extends "base.html" %}
{% block app_content %}
<br>
<h5 class="display-5">Here are the latest numbers of coronavirus cases and death in  {{ state }} state</h5>
<br>
<br>

<div class="col-md-6" id="changes_table">

{{ table }}

</div>
<script>
$(document).ready(function() {
    $("table").DataTable( {
        columnDefs: []
    } );
} );
</script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block app_content %}

    <h6>Please select the state from the menu and press the "Submit" button </h6>
    <br>
<div class="col-sm-12 col-md-2" id="state_selection">

<form action="{{ url_for('routes.index') }}" method="post">
    <d1>
    {{states_form.csrf_token}}
    {{ wtf.quick_form(states_form) }}
    {{wtf.form_errors(states_form, hiddens=False)}}

        <input class="btn btn-primary" type="submit" value="Submit">

    </d1>

</form>
</div>

{% endblock %}